---
title: "Criticality of Boolean functions"
author: "Tulasimohan Molli"
date: "2023-10-05"
categories: [Boolean formulae, Criticality]
tags: [complexity]
bibliography: ../../assets/bibliography/My Library.bib
draft: true
---

$\newcommand{\zo}{\{0,1\}}$ **Question**: What is Criticality? <br> **Answer:** Defined by Rossman in [@rossman2019] is a complexity measure for Boolean functions which captures the essence of Swithching Lemma.

**Question:** So, What is a Switching lemma? <br> **Answer:** Switching lemma studies the effect of random restrictions on depth 2 formulae i.e. DNFs and CNFs.

**Question:** So, what is a random restriction?

## Random restrictions

A $p$ -random restriction is distribution on the partial inputs. Each variable is independetly revealed with probability $p$ and hidden with probability $1-p$. When revealed it is set to 0 or 1 randomly. Here is a formal defintion,

::: {.callout-note icon="false"}
## $p$ random restriction

Let $X$ be the set of variables. A restriction $\rho$ is a map $\rho: X \to \{0,1,*\}$. A $p$-random restriction is sampled as follows: - For each $i \in n$, $$x_i = \begin{cases}
&* \text{\ with prob\ } p\\
&0 \text{\ with prob\ } (1-p)/2\\
&1 \text{\ with prob\ } (1-p)/2.
\end{cases}$$
:::

## Hastad's switching lemma

Hastad in his Godel prize work on switching lemmas has studied the effect of random restrictions on depth 2 formulas i.e. DNF and CNF with bounded with. He showed that depth 2 formulas of bounded width become small depth decision trees with whp.

-   To this date there are two proofs of this theorem available. One due to Hastad and the other due to Razabraov.

-   Razbarov uses an encoding argument and the notion of a canonical decision tree.

Since a decision tree of depth$k$ can be converted into a DNF and CNF of width $k$, this can be used switch a DNF to CNF and vice-versa. Hence the name Switching lemma.

### Applications of HSL

This has found many applications in Circuit Complexity.

-   An application of the HSL proved in the original paper[@hastad1986] of Hastad is the tight size lower bound on $AC^0$ circuits computing parity.

-   Following the Switching lemma [@linial1993] showed Fourier tail bounds which implied learning algorithms for DNFs and CNFs.

-   Bazzi [@bazzi2009]and Braverman[@braverman2010] constructed PRGs for DNFs and $AC^0$ circuits respectively. They works showed that bounded independence fools $AC^0$ circuits.

## AC0 formulae

-   Meanwhile [@rossman2018] showed tight lower bounds for $AC^0$ formulae using using a very clever application Hastad's switching lemma.

    -   This result implies the $AC^0$ circuit lower bound.

    -   A size $S$ circuit of depth can be converted into a size $S^d$ Formula of depth by starting from the bottom and carefully duplicating the nodes which are used more than once. Rossman Formula lower bound showed that this conversion is tight. [^1]

[^1]: Why? Suppose this conversion is not tight, size \$$S$ circuit became $o(S^d)$ formula, then this would imply a too good to be true cirucit lower bound for $AC^0$ circuits

## Average case lower bounds

-   Hastad came up with his multi switching lemma and showed a Average case lower bound for $AC^0$ circuits. In doing so, he drastically simplifies his original proof of the HSL.

    -   In this proof, he comes with the notion of Downward closed set of restrictions and notes that certain events are downward closed and magically finishes the proof in a few lines.

    -   He constructs common decision trees for a collection of Boolean functions.

## One theorem to prove them all

So far, we have seen Circuits and Formulae.

-   Worst and Average case size lower bounds for $AC^0$ Cirucits. Both due to Hastad.

-   Worst case size lower bound for $AC^0$ formulae.

::: {.callout-caution icon="false"}
### Question:

Average case lower bounds for $AC^0$ formulae.
:::

Why do we care?

-   Implies all the other lower bounds that we mentioned till this point.

## Criticality

Enters Rossman with his notion of Criticality inspired by the statement of HSL.

-   Shows that all existing bounds are just bounds on Criticality. - \[ \] write this.

-   Bounds on Criticality imply all the applications, like

    -   Worst and Average case size lower bounds.

    -   Fourier tail bounds.

    -   Learning Algorithms.

    -   Satisfiability algorithms.

    -   Bounds on decision trees size.

-   Conjectures that the Criticality of $AC^0$ formulae of size $S$ and depth $d+1$ is $\frac1d \left(\frac{\log S}{d}\right)^d$.

-   Proved the conjecture for \$$d =1$ i.e. CNFs and DNFs using some Entropic arguments.

-   Proved the conjecture for Regular \$$AC^0$ formulae in [@rossman2019].

-   The general formula case was resolved by [@harsha2023].

## Key ideas

-   Canonical Decsion tree

-   Razborov's encoding proof

-   Downward closure

-   Canonical Common Decision trees

-   Hastad's downward closure proof

-   Coupled sampling procedure for Sampling random restrictions

-   Tree Restrictions

-   Rossman's Canonical Decision Tree for Formulae.

-   Rossman's Entropic proof for DNFs and Regular formulae.