name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.6.40

      - name: Render Quarto Project
        run: |
          quarto render

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp://webserver07.fc.ul.pt
          username: tmolli@ciencias.ulisboa.pt
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: docs/
          protocol: sftp
          port: 22
          server-dir: /public_html/
          dangerous-clean-slate: true
